download_sem: 3
download_retry: 3
update_cron: 35 6 * * *
update_tz: Asia/Shanghai

domian: http://0.0.0.0:46199
host: 0.0.0.0
port: 46199
urlprefix: /path/to/mess/url

subscribes:
  JMS:
    type: jms
    url: https://jmssub.net/members/getsub.php?service=<service>&id=<id>
    counter: https://justmysocks5.net/members/getbwcounter.php?service=<service>&id=<id>
    subtz: America/Los_Angeles
profiles:
  JMS-blacklist:
    template: blacklist
    subs:
      - JMS
  whitelist-jms:
    template: whitelist
    subs:
      - JMS
